spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?createDatabaseIfNotExist=true
    username: root
    password: root
server:
  port: 8080